version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./website/
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend